# Test Case: YARA Enable/Disable
# Validates that YARA can be enabled and disabled successfully

metadata:
  test_id: "TEST-001"
  jira_ticket: "CORE-5432"
  title: "YARA Enable/Disable Test"
  description: |
    This test validates that the YARA feature can be successfully enabled
    and disabled on the sensor without causing service failures.

  priority: "high"
  category: "functional"
  tags:
    - "yara"
    - "features"
    - "configuration"

  author: "QA Team"
  created: "2025-10-10"
  last_updated: "2025-10-10"
  version: "1.0"

sensor:
  version_min: "28.0.0"
  version_max: null
  required_features: []
  required_packages: []

# Test setup
setup:
  - action: "create_snapshot"
    params:
      snapshot_name: "yara-test-baseline"
    description: "Create baseline snapshot for rollback"

# Main test steps
steps:
  - step: 1
    description: "Get current YARA status"
    action: "get_config"
    params:
      key: "corelight.yara.enable"
    expected:
      type: "regex"
      value: "^(True|False|true|false)$"
    on_failure: "abort"

  - step: 2
    description: "Enable YARA feature"
    action: "set_config"
    params:
      key: "corelight.yara.enable"
      value: "True"
    expected:
      type: "exit_code"
      value: 0
    on_failure: "abort"

  - step: 3
    description: "Wait for service restart"
    action: "wait"
    params:
      duration: 30
    expected:
      type: "exit_code"
      value: 0
    on_failure: "continue"

  - step: 4
    description: "Verify YARA is enabled"
    action: "get_config"
    params:
      key: "corelight.yara.enable"
    expected:
      type: "contains"
      value: "True"
    on_failure: "abort"

  - step: 5
    description: "Check sensor status after enable"
    action: "ssh_command"
    params:
      command: "sudo corelightctl sensor status"
    expected:
      type: "contains"
      value: "OK"
    on_failure: "abort"

  - step: 6
    description: "Disable YARA feature"
    action: "set_config"
    params:
      key: "corelight.yara.enable"
      value: "False"
    expected:
      type: "exit_code"
      value: 0
    on_failure: "abort"

  - step: 7
    description: "Wait for service restart"
    action: "wait"
    params:
      duration: 30
    expected:
      type: "exit_code"
      value: 0
    on_failure: "continue"

  - step: 8
    description: "Verify YARA is disabled"
    action: "get_config"
    params:
      key: "corelight.yara.enable"
    expected:
      type: "contains"
      value: "False"
    on_failure: "abort"

  - step: 9
    description: "Check sensor status after disable"
    action: "ssh_command"
    params:
      command: "sudo corelightctl sensor status"
    expected:
      type: "contains"
      value: "OK"
    on_failure: "abort"

# Test cleanup
cleanup:
  - action: "restore_snapshot"
    params:
      snapshot_name: "yara-test-baseline"
    description: "Restore to baseline state"

# Expected results
expected_results:
  overall_status: "passed"
  steps_passed: 9
  steps_failed: 0
  duration_max: 300

# Test validation criteria
validation:
  - type: "all_steps_passed"
    description: "All test steps must pass"

  - type: "duration_within_limit"
    description: "Test must complete within 5 minutes"

notes: |
  Test validates JIRA-5432: YARA enable/disable functionality

  Prerequisites:
  - Sensor must be deployed and accessible
  - SSH credentials must be configured in .env

  Expected behavior:
  - YARA can be enabled without errors
  - YARA can be disabled without errors
  - Sensor services remain healthy throughout
