# Test Case: Sensor Health Check
# Comprehensive sensor health validation

metadata:
  test_id: "TEST-003"
  jira_ticket: "CORE-6001"
  title: "Comprehensive Sensor Health Check"
  description: |
    This test performs a comprehensive health check of the sensor,
    validating all critical services, disk space, memory usage,
    and network connectivity.

  priority: "medium"
  category: "regression"
  tags:
    - "health-check"
    - "monitoring"
    - "regression"

  author: "QA Team"
  created: "2025-10-10"
  last_updated: "2025-10-10"
  version: "1.0"

sensor:
  version_min: "28.0.0"
  version_max: null
  required_features: []
  required_packages: []

# Test setup
setup: []

# Main test steps
steps:
  - step: 1
    description: "Check overall sensor status"
    action: "ssh_command"
    params:
      command: "sudo corelightctl sensor status"
    expected:
      type: "contains"
      value: "OK"
    on_failure: "abort"

  - step: 2
    description: "Verify Zeek service is running"
    action: "ssh_command"
    params:
      command: "sudo systemctl is-active zeek"
    expected:
      type: "contains"
      value: "active"
    on_failure: "abort"

  - step: 3
    description: "Check disk space usage (root partition)"
    action: "ssh_command"
    params:
      command: "df -h / | tail -1 | awk '{print $5}' | sed 's/%//'"
    expected:
      type: "regex"
      value: "^([0-9]|[1-8][0-9])$"
    on_failure: "continue"

  - step: 4
    description: "Check memory usage"
    action: "ssh_command"
    params:
      command: "free | grep Mem | awk '{printf \"%.0f\", ($3/$2) * 100}'"
    expected:
      type: "regex"
      value: "^([0-9]|[1-9][0-9])$"
    on_failure: "continue"

  - step: 5
    description: "Verify sensor is capturing traffic"
    action: "ssh_command"
    params:
      command: "sudo zeek-netstats | grep packets"
    expected:
      type: "contains"
      value: "packets"
    on_failure: "continue"

  - step: 6
    description: "Check for critical errors in logs"
    action: "ssh_command"
    params:
      command: "sudo journalctl -u zeek -n 100 --no-pager | grep -i 'error' | wc -l"
    expected:
      type: "equals"
      value: "0"
    on_failure: "continue"

  - step: 7
    description: "Verify sensor configuration is valid"
    action: "ssh_command"
    params:
      command: "sudo corelightctl sensor configuration validate"
    expected:
      type: "exit_code"
      value: 0
    on_failure: "abort"

  - step: 8
    description: "Check CPU load average (1 min)"
    action: "ssh_command"
    params:
      command: "uptime | awk '{print $10}' | sed 's/,//'"
    expected:
      type: "regex"
      value: "^[0-9]+\\.?[0-9]*$"
    on_failure: "continue"

  - step: 9
    description: "Verify network interfaces are up"
    action: "ssh_command"
    params:
      command: "ip link show | grep -c 'state UP'"
    expected:
      type: "regex"
      value: "^[1-9][0-9]*$"
    on_failure: "abort"

  - step: 10
    description: "Check sensor license status"
    action: "ssh_command"
    params:
      command: "sudo corelightctl sensor license status"
    expected:
      type: "contains"
      value: "valid"
    on_failure: "continue"

# Test cleanup
cleanup: []

# Expected results
expected_results:
  overall_status: "passed"
  steps_passed: 10
  steps_failed: 0
  duration_max: 120

# Test validation criteria
validation:
  - type: "all_steps_passed"
    description: "All health checks must pass"

  - type: "duration_within_limit"
    description: "Health check must complete within 2 minutes"

  - type: "no_service_errors"
    description: "No critical service errors"

notes: |
  Test validates JIRA-6001: Comprehensive sensor health check

  This test is designed to run frequently as part of regression testing
  to ensure sensor stability and health.

  Prerequisites:
  - Sensor must be deployed and running
  - All critical services should be started

  Health Check Items:
  1. Overall sensor status
  2. Critical services (Zeek)
  3. Disk space (<90% usage)
  4. Memory usage (<95% usage)
  5. Traffic capture active
  6. No critical errors in logs
  7. Configuration validity
  8. CPU load
  9. Network interfaces
  10. License status

  Pass Criteria:
  - All critical checks (steps 1, 2, 7, 9) must pass
  - Resource checks (steps 3, 4, 8) may warn but don't fail test
  - Log check (step 6) may have non-critical errors
